### ISSUE TITLE
能否参考此脚本做收集装置

### ISSUE THREAD

**Issue by q82415670** [DokiDoki1103/tikuAdapter#13]
https://tcb-w644nfbyxrttaih-2cpr71dbf4b7-1304481250.tcloudbaseapp.com/fcq26.user.js

**Comment by q82415670** [comment]
这个脚本的自动提取功能很不错  如果提取完能上传到本体题库就太好了

**Comment by DokiDoki1103** [comment]
脚本和软件是不一样的概念，脚本可以运行在浏览器中，但是软件是无法运行在浏览器中的，所以无法做浏览器采集的功能。

**Comment by q82415670** [comment]
那有什么办法可以将[
  {
    "id": "",
    "title": "蛋氨酸和苯丙氨酸在体内可分别转化为",
    "type": "单选题",
    "select": [
      "亮氨酸和酪氨酸",
      "苏氨酸和缬氨酸",
      "半胱氨酸和酪氨酸",
      "胱氨酸和脯氨酸"
    ],
    "owner": [],
    "answer": [
      "C                    半胱氨酸和酪氨酸",
      "半胱氨酸和酪氨酸"
    ],
    "wrong": []
  }
]
类似这样的内容识别并导入到数据库里呢

**Comment by DokiDoki1103** [comment]
暂时没有办法 ，这种格式只是他的规范而已，并不满足我们的规范
