### ISSUE TITLE
为什么我这个默认禁用了万能题库

### ISSUE THREAD

**Issue by q82415670** [DokiDoki1103/tikuAdapter#14]
![image](https://github.com/DokiDoki1103/tikuAdapter/assets/110165439/db2c98f8-7e7c-4304-ab24-72a042d01bc4)
http://localhost:8060/adapter-service/search?wannengToken=**********&aidianYToken=********************

**Comment by q82415670** [comment]
我输入的是这一串  然后不知道为什么默认万能题库是关闭的

**Comment by DokiDoki1103** [comment]
如果在万能脚本中使用了 tikuAdapter， 他将会自动禁用 万能题库，因为脚本会搜一次题，tikuAdaper也会搜一次，造成重复搜索，所以**万能脚本**默认禁用了万能题库，而不是我们程序禁用了万能题库
