### ISSUE TITLE
还缺少一个自定义题库的配置方案

### ISSUE THREAD

**Issue by chenshiforever** [DokiDoki1103/tikuAdapter#15]
比如自己的题库想要用这个聚合器，然后最好是能够用ip+端口访问的形式，自己的题库不一定有域名。

**Comment by chenshiforever** [comment]
然后还可以把配置文件单独写在config.json里面，不用全部写在地址栏里面，就像答题姬的config一样[https://github.com/SocialSisterYi/CxKitty/blob/main/config.yml](https://github.com/SocialSisterYi/CxKitty/blob/main/config.yml)

**Comment by DokiDoki1103** [comment]
> 比如自己的题库想要用这个聚合器，然后最好是能够用ip+端口访问的形式，自己的题库不一定有域名。

https://github.com/DokiDoki1103/tikuAdapter#%E4%BD%BF%E7%94%A8api%E6%8E%A5%E5%8F%A3

上述就是IP+端口的格式，只不过是本地的IP而已，你有服务器直接替换成服务器的IP即可。

**Comment by DokiDoki1103** [comment]
> 然后还可以把配置文件单独写在config.json里面，不用全部写在地址栏里面，就像答题姬的config一样https://github.com/SocialSisterYi/CxKitty/blob/main/config.yml

如果写在配置文件里，那么耦合性将大大提高。很多场景将不被支持。

- 用户觉得A题库的选择题正确率较高，那么只使用题库A，而不使用其他题库
- 用户搭建了题库接口，想要分享给其他人使用，总不能配置文件写死，让所有人用他自己的Token

如果将 题库配置写在url中。那么自定义程度大大提高

**Comment by chenshiforever** [comment]
不是不是，就是我的意思是如果我有接口http://88.88.88.88:8088,这个应该怎么插入进去呢，，

**Comment by chenshiforever** [comment]
我的意思是我自己的接口用你的这个耦合器分享出来

**Comment by DokiDoki1103** [comment]
你想要分享你的题库接口？适配到tikuAdapter？那真是太好了！我愿意为你适配你的题库。

**Comment by chenshiforever** [comment]
我的意思就是缺一个自己可以增加自定义题库的

**Comment by DokiDoki1103** [comment]
目前的解决方案是采取了硬编码方式增加题库，不过你的想法很新颖，我将会在下一个版本中添加它。

**Comment by chenshiforever** [comment]
还有一个建议，就是能够把题库出来的原题也返回出来，如果题库返回了question的话。

**Comment by DokiDoki1103** [comment]
> 还有一个建议，就是能够把题库出来的原题也返回出来，如果题库返回了question的话。

不可以，因为answe字段有限，只能表述答案，返回原题库问题，并不满足规范。

另外，大多数题库都是不返回问题的，只有答案。

**Comment by chenshiforever** [comment]
爱点的就有题目呀。可以增加一个字段嘛，这样的话更容易识别。

**Comment by DokiDoki1103** [comment]
你觉得应该增加在哪？

**Comment by DokiDoki1103** [comment]
怎么样子增加才能和 answer数组一一对应？

**Comment by DokiDoki1103** [comment]
<img width="1006" alt="图片" src="https://github.com/DokiDoki1103/tikuAdapter/assets/62740231/75d8ceff-56cc-4bc5-b2e4-8d56d49be8f2">

许多接口的答案返回聚合在一起，你觉得你的问题能加在哪里和答案一一对应？

**Comment by DokiDoki1103** [comment]
https://github.com/DokiDoki1103/tikuAdapter/commit/315c1c083224bd1ac8ac58f3df8edd723f6f901e

**Comment by chenshiforever** [comment]
增加一个orgin字段，`orgin:{question:xxx,options:xxx,answer:xxx}`

**Comment by chenshiforever** [comment]
测试了一下，windows平台get请求中文乱码~

**Comment by DokiDoki1103** [comment]
> 测试了一下，windows平台get请求中文乱码~

- 本issue主题是 【自定义题库配置方案】与你的乱码问题毫不相干。
- 另外请不要在已经关闭的issue中继续提问。
