### ISSUE TITLE
没有搜索本地题库的功能

### ISSUE THREAD

**Issue by 1302557841** [DokiDoki1103/tikuAdapter#20]
没有搜索本地题库的功能
只能慢慢查找，能否修改一下呢

**Comment by DokiDoki1103** [comment]
目前您只能通过将 右下角的 页码放大，然后 `ctrl + f `使用浏览器的搜索功能

**Comment by DokiDoki1103** [comment]
https://github.com/DokiDoki1103/tikuAdapter/commit/f1ef50f657b7c686e8a91a96b9fa2135c1026774
