### ISSUE TITLE
试了很多次还是不会用

### ISSUE THREAD

**Issue by saye04** [DokiDoki1103/tikuAdapter#24]
大佬你好，是这样的，我想把他对接到答题姬上使用（这样也可以省下不少题库费用）但是好像那个我不太会对接，怎么弄都对接不了，您可以帮我试试吗？谢谢！

**Comment by DokiDoki1103** [comment]
首页有api调用说明，你可以详细查看api说明，看看咱们的接口是如何调用的

**Comment by saye04** [comment]
> > 大佬你好，是这样的，我想把他对接到答题姬上使用（这样也可以省下不少题库费用）但是好像那个我不太会对接，怎么弄都对接不了，您可以帮我试试吗？谢谢！
> 
> 学会了没
> 

没有😭
