### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by 2173505570** [DokiDoki1103/tikuAdapter#26]
大佬我有window服务器，有域名，能不能求教怎么部署到服务器，我直接在服务器运行exe，在客户端用公网ip加端口的方式没办法请求，go语言也不会请求大佬帮助，感谢感谢

**Comment by DokiDoki1103** [comment]
ip : 端口 8060

**Comment by DokiDoki1103** [comment]
http://localhost:8060/adapter-service/search

localhost 变成ip
