### ISSUE TITLE
查询过的题目未保存到本地数据库

### ISSUE THREAD

**Issue by c90c90** [DokiDoki1103/tikuAdapter#28]
版本：v0.1.0-beta.7
系统：windows11-amd64
问题：已经配置config.yaml文件，其中recordEmptyAnswer: true，未配置mysql，根据作者在 https://github.com/DokiDoki1103/tikuAdapter/issues/5#issuecomment-1793350969 的回复，查询过的题目应该保存到本地，二次查询不再调用接口，但是查询题目后本地tiku.db文件大小并未发生变化，控制台无查询请求外的其他日志
localhost:8060中也没有任何数据

**Comment by 1302557841** [comment]
+1

**Comment by j815551469** [comment]
+1
