### ISSUE TITLE
v0.1.0-beta.13 加入用户管理系统后无法正常启动应用程序

### ISSUE THREAD

**Issue by wojiaoyishang** [DokiDoki1103/tikuAdapter#35]
无数据库文件时启动（首次启动）：
![image](https://github.com/user-attachments/assets/bf3b3e6d-0149-4c66-94be-ede78a06eec5)

数据库文件生成后启动（再次启动）：
![image](https://github.com/user-attachments/assets/776bb323-ab9b-4fce-862c-64db0a2fbcd1)

经过测试，这个问题出现在 v0.1.0-beta.13 的时候。

v0.1.0-beta.13 之前正常，应该是用户信息创建逻辑有误。

**Comment by wojiaoyishang** [comment]
同时我在 linux 上运行过最新版，也在 docker 中构建过最新版，问题同样存在

**Comment by DokiDoki1103** [comment]
[FATAL] 2024/08/06 - 23:46:42 | [bucket name len is between [3-63],now is 0]
阿里云 配置有误则启动失败，应该没配置的情况下不加载oss，我来修复

**Comment by DokiDoki1103** [comment]
fix: fix: https://github.com/DokiDoki1103/tikuAdapter/releases/tag/v0.1.0-beta.16
