### ISSUE TITLE
【bug】我在使用beta16时通过web无法删除已保存的题目

### ISSUE THREAD

**Issue by guowang23333** [DokiDoki1103/tikuAdapter#37]
我无法删除和编辑已保存的题目
![image](https://github.com/user-attachments/assets/ec923937-fe91-4465-84e7-8814ea41319c)
我想是因为id这一列为0
![image](https://github.com/user-attachments/assets/666bcdf9-6058-4c1b-9294-2ea6e482d832)
具体为什么id这一列为0我目前不清楚

**Comment by guowang23333** [comment]
我一直在使用万能题库来自动存储答案，应该也不是账号权限的问题。我直接应用的exe文件搭配config使用
![image](https://github.com/user-attachments/assets/a94e4770-55d8-4127-a99d-86a31a012571)

**Comment by guowang23333** [comment]
顺手说一下老哥能不能搞一个接口来录入题目+答案比如post请求什么的

**Comment by DokiDoki1103** [comment]
fix：https://github.com/DokiDoki1103/tikuAdapter/releases/tag/v0.1.0-beta.17
