### ISSUE TITLE
win上api失败&建议网页端支持设置题库token

### ISSUE THREAD

**Issue by wuchen-beifeng** [DokiDoki1103/tikuAdapter#38]
网页端支持设置题库token
win上api失败
链接：http://localhost:8060/adapter-service/search?use=icodef&icodefToken=IB5vLw6cpB7EVEnh 
提交数据：{"question": " 关于评价一个人心理是否健康需要注意各方面的表述，下列表述哪一项是错误的（   ）","options": ["心理不健康往往在某个方面所表现出或轻或重的失调","心理健康是相对的，即相对于大多数人的心理状况而言","心理健康并不是一种静态的平衡，而是与现实环境保持动态协调","心理健康是绝对的，相对于特殊人群的心理状况而言"],"type": 0 }
返回数据：{"plat":0,"question":" 关于评价一个人心理是否健康需要注意各方面的表述，下列表述哪一项是错误的（   ）","options":["心理不健康往往在某个方面所表现出或轻或重的失调","心理健康并不是一种静态的平衡,而是与现实环境保持动态协调","心理健康是相对的,即相对于大多数人的心理状况而言","心理健康是绝对的,相对于特殊人群的心理状况而言"],"type":0,"answer":{"answerKey":[],"answerKeyText":"","answerIndex":[],"answerText":"","bestAnswer":[],"allAnswer":[]}}
公众号返回
![image](https://github.com/user-attachments/assets/acd0d598-fea0-418d-8fd3-624b68501da8)

**Comment by DokiDoki1103** [comment]
<img width="930" alt="图片" src="https://github.com/user-attachments/assets/94248427-2885-42c3-a307-aa432071d048">
icodef的接口无法返回答案，可能公众号和api接口不同
