### ISSUE TITLE
教程

### ISSUE THREAD

**Issue by zhc20040214** [DokiDoki1103/tikuAdapter#44]
能否出一个搭建教程，直接解压到宝塔里运行不了

**Comment by Xiao-0417** [comment]
从release下载你服务器对应架构的包，解压之后直接运行就好了啊，你是不是下source code去了？

**Comment by DokiDoki1103** [comment]
https://github.com/DokiDoki1103/tikuAdapter?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2%E4%BD%BF%E7%94%A8
