### ISSUE TITLE
感觉题库调用似乎有点小问题？

### ISSUE THREAD

**Issue by Xiao-0417** [DokiDoki1103/tikuAdapter#45]
感觉很少调用到付费题库，有的时候是免费题库有的就直接免费题库了，正确率有点低......
可以添加一个题库权重？比如优先使用A题库，A题库没有再去请求B题库，或者是一道半请求A题库，一般请求B题库.....这样（似乎有那么一点点不是太好做啊哈啊哈）

**Comment by DokiDoki1103** [comment]
如果你想调用一些特殊的付费题库，都需要添加参数，例如`wannengToken`
现在的逻辑是，一次性全部调用所有的题库，然后聚合答案返回。你说的先使用A再使用B再使用C容易导致超时

**Comment by Xiao-0417** [comment]
现在的问题是这样.....我只调用了wanneng题库（url是这样：http://localhost:8060/adapter-service/search?use=wanneng&wannengToken=myTokenStr）但是我的正确率很低，我直接用万能可能正确率是90%甚至100%，但用这个聚合搜索之后，正确率就会降低，只有70%甚至60%.......
然后.......具体看日志的话，好像万能题库付费接口调用出现了一些不太对劲的地方？是我频率太高了么？
![Screenshot_2024-10-09-14-40-31-101_com termux](https://github.com/user-attachments/assets/1540ee94-2f11-4ba9-a5ff-f44f31736dbe)

**Comment by DokiDoki1103** [comment]
首先你要确保，question，options，type这三个通用字段传递正确，其次万能题库有限流措施，你请求的频繁他会返回429就不会返回答案了

**Comment by Xiao-0417** [comment]
> 首先你要确保，question，options，type这三个通用字段传递正确，其次万能题库有限流措施，你请求的频繁他会返回429就不会返回答案了

我请求是5秒一题，应该达不到阈值

**Comment by DokiDoki1103** [comment]
5s没问题啊，你传的参数是什么？什么题出错的概率比较高，然后把参数发我

**Comment by Xiao-0417** [comment]
> 你调用万能接口的时候，你传参数是什么样的？调用tikuAdapter的传参数是什么

我是在OCS里调用的tikuAdapter，直接给了链接，其他的请求都是代码里原本设置的，我没有改动

**Comment by DokiDoki1103** [comment]
这大概率是ocs代码匹配逻辑的问题啦

**Comment by Xiao-0417** [comment]
> 这大概率是ocs代码匹配逻辑的问题啦

昂～～OCS的问题吼......那行，我换个别的啊哈
