### ISSUE TITLE
无法导入题库啊

### ISSUE THREAD

**Issue by qq666666qq** [DokiDoki1103/tikuAdapter#50]
无法导入题库啊
[1.docx](https://github.com/user-attachments/files/17663368/1.docx)
![image](https://github.com/user-attachments/assets/b4a0fa09-644b-46c0-bcf8-a3e8ce9adfeb)
点导入没有反应，

**Comment by qq666666qq** [comment]
希望大佬解答一下，谢谢

**Comment by qq666666qq** [comment]
https://github.com/user-attachments/files/17663368/1.docx

**Comment by DokiDoki1103** [comment]
TypeError: t.options is undefined 确认是一个前端BUG @xuzhonglin12138

**Comment by Run-os** [comment]
佬，请问啥时候可以更新修复啊，找了好久目前就看到该项目可以做到本地导入题目，用api搜题 @xuzhonglin12138

**Comment by NUnzOSz** [comment]
我把报错处的代码，web\src\pages\IntelligentImport里的index.vue第237行的“data.options.length > 0”改为“data.options != undefined”，本地编译运行发现可以导入了，不知道会不会有其他的bug。

**Comment by xuzhonglin12138** [comment]
问题已修复，原因是在对options字段做判断不为空时，没有考虑到options字段可能不是数组的情况，导致data.options.length报错。所以点击按钮无法提交。 @qq666666qq 
另外针对你提供的1.docx这种大文件，我们做了一些优化： 接口报错处理，超时处理，按钮loading状态等

**Comment by yuanxing109** [comment]
> 问题已修复，原因是在对options字段做判断不为空时，没有考虑到options字段可能不是数组的情况，导致data.options.length报错。所以点击按钮无法提交。 @qq666666qq 另外针对你提供的1.docx这种大文件，我们做了一些优化： 接口报错处理，超时处理，按钮loading状态等

更新了还是不行
使用的termux运行的tikuAdapter提交不了没有反应

**Comment by xuzhonglin12138** [comment]
提交的PR未合并，所以你拉取的代码还是未更新的代码。 @yuanxing109 
合并一下 @DokiDoki1103

**Comment by DokiDoki1103** [comment]
v0.1.0-beta.29 版本已经修复，但是导入的题库智能精确匹配，好像意义不大， 目前还不支持模糊搜索
