### ISSUE TITLE
用ocs和万能的问题

### ISSUE THREAD

**Issue by qq666666qq** [DokiDoki1103/tikuAdapter#51]
ocs只能用一个题库，多个会搜不到题。
万能搜到提后不会自动储存到本地题库，

**Comment by qq666666qq** [comment]
不过这些问题不大，希望word导入能尽快修复，或者以前的版本有哪个能用word导入么，大佬

**Comment by qq666666qq** [comment]
非常感谢各位大佬的开发

**Comment by DokiDoki1103** [comment]
> 不过这些问题不大，希望word导入能尽快修复，或者以前的版本有哪个能用word导入么，大佬

这个等我修复，近期会解决

**Comment by qq666666qq** [comment]
> > ocs只能用一个题库，多个会搜不到题。 万能搜到提后不会自动储存到本地题库，
> 
> 会自动记录到题库啊，下次就可以直接搜到了，如果要记录空答案就要加配置文件recordEmptyAnswer: true

2024/11/08 21:09:09 /home/runner/work/tikuAdapter/tikuAdapter/internal/dao/tiku.gen.go:280 constraint failed: UNIQUE constraint failed: tiku.hash (2067)
[0.507ms] [rows:0] INSERT INTO `tiku` (`question`,`type`,`options`,`answer`,`plat`,`hash`,`course_name`,`extra`) VALUES ("庄子说:“方生方死，方死方生;方可方不可，方不可方可。”这个命题表现的哲学思想是()",0,"[\"承认事物是变化的\",\"承认事物的 变化是灵活多样的\",\"是否认相对静止的相对主义观点\",\"是辩证法的运动观\"]","[]",0,"40d56718da2601486b9907622d2eaff4","","") RETURNING `id`

2024/11/08 21:09:09 /home/runner/work/tikuAdapter/tikuAdapter/internal/dao/tiku.gen.go:297
[0.526ms] [rows:1] SELECT * FROM `tiku` WHERE `tiku`.`hash` = "40d56718da2601486b9907622d2eaff4" ORDER BY `tiku`.`id` LIMIT 1
[GIN] 2024/11/08 - 21:09:09 | 200 |    173.8191ms |             ::1 | POST     "/adapter-service/search?use=local"
第一次用万能，言希，icor题库把题了录入，然后改成local，搜不到提

**Comment by qq666666qq** [comment]
![image](https://github.com/user-attachments/assets/054a30fe-09c8-4339-8a2d-45d4e9281bdd)

**Comment by qq666666qq** [comment]
limit:
  enable: false # 是否开启
  duration: 3  # 时间窗口为3秒
  requests: 1  # 允许用户在3秒内通过1个请求

api:
  - name: '样例接口 json 请求'
    enable: false
    url: http://lyck6.cn/scriptService/api/autoFreeAnswer
    method: POST
    headers:
      - key: Content-Type
        value: application/json
    body: '{"question":"${question}"}'
    answer: 'result.answers.0.0'

  - name: '样例接口 表单请求'
    enable: false
    url: https://cx.icodef.com/wyn-nb?v=4
    method: POST
    headers:
      - key: Content-Type
        value: application/x-www-form-urlencoded
    body: 'question=${question}'
    answer: 'data'

  
recordEmptyAnswer: true # 是否记录空答案（开启之后即便没有答案也会记录在数据库方便后期手动整理题库）

**Comment by DokiDoki1103** [comment]
你直接打开 localhost:8060,登录看看是否有记录到题库

**Comment by qq666666qq** [comment]
![image](https://github.com/user-attachments/assets/cae898a8-a4e5-41ae-ad52-9ac1991bdb42)
好像都是没有选择答案

**Comment by qq666666qq** [comment]
e不太清楚，用一个题库就好了

**Comment by DokiDoki1103** [comment]
两个题库你的url是怎么写的
