### ISSUE TITLE
万能答题不会先搜题库的答案

### ISSUE THREAD

**Issue by qq666666qq** [DokiDoki1103/tikuAdapter#55]
![image](https://github.com/user-attachments/assets/6b315838-73cf-4737-b504-822fc0b99a5a)
![image](https://github.com/user-attachments/assets/a3c0a50f-dd30-4d92-bb36-264bbccfb631)
http://localhost:8060/adapter-service/search?use=local,wanneng,icodef&icodefToken=TXXXXXXXXXX
[日志.txt](https://github.com/user-attachments/files/18038960/default.txt)

**Comment by qq666666qq** [comment]
![image](https://github.com/user-attachments/assets/9a436226-4bb7-4dc6-84ed-875d432176e2)

**Comment by wanwuone** [comment]
我也是这样，不知道是不是请求地址写错了，我写的这个[http://localhost:8060/adapter-service/search?use=local]

**Comment by DokiDoki1103** [comment]
因为万能题库作者不允许将它的题库缓存至本地，在他脚本里面写死的，所以无法支持缓存万能题库
